title: "Script and Pad"
description: "Home of Screenplay Writer and tools for writers."
url: "https://scriptandpad.com"
theme: minima
permalink: /:title/
markdown: kramdown
author: "Script and Pad"
default_image: "https://scriptandpad.com/logo.png"
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll/tagging
